<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-LuisHermenegildo1/blob/main/PythonCourse_Module_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Modulo 5**

**Ciencia de datos**

In [2]:
import numpy as np

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [3]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [4]:
a = [[1,2,3],[4,5,6],[6,3,4]]
A = np.array(a)
A

array([[1, 2, 3],
       [4, 5, 6],
       [6, 3, 4]])

In [5]:
A.ndim

2

In [6]:
A.shape

(3, 3)

In [7]:
A.size  

9

In [8]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A.size

8

In [9]:
##ERROR##
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

#np.dot(A,B)

What is the result of the following lines of code:

In [10]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

What is the result of the following lines of code:


In [11]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [12]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])